#!/bin/bash

APP_PORT=45000
FW_RULE_NUM=59

case "${1}" in
    setup)
        sudo ifconfig lo0 alias 169.254.169.254
        sudo ipfw add ${FW_RULE_NUM} fwd 169.254.169.254,${APP_PORT} tcp from any to 169.254.169.254 80 in
        ;;

    teardown)
        sudo ifconfig lo0 -alias 169.254.169.254
        sudo ipfw delete ${FW_RULE_NUM}
        ;;

    *)
        echo >&2 "Unknown command: ${1}"
        echo >&2 "Commands: setup, teardown"
        exit 1
        ;;
esac

